# Step
stages:
  - setup
  - deploy

# When using dind, it's wise to use the overlayfs driver for
# improved performance.few
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH

# Setup Nginx
deploy-nginx:
  image: docker:stable
  stage: setup
  labels:
    com.docker.lb.ssl_cert: demo_app.example.org.cert
    com.docker.lb.ssl_key: demo_app.example.org.key
  before_script:
    - "apk update"
    - "apk add --no-cache py-pip rsync git openssh"
    - "pip install --no-cache-dir docker-compose"
    - "git submodule update --init --recursive"
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
    - chmod 700 "${HOME}/.ssh/id_rsa"
    - addgroup -g 1000 -S nginx && adduser -u 1000 -D -S -G nginx nginx
    - rsync -hrvz --delete --exclude=_ -e "ssh -i ${HOME}/.ssh/id_rsa" nginx-setting "${LINUX_USERNAME}@${HOST_IP}:/home/$LINUX_USERNAME/"
  script:
    - "docker-compose -f .cd/docker-compose.nginx.yml pull"
    - "docker-compose -f .cd/docker-compose.nginx.yml stop"
    - "docker-compose -f .cd/docker-compose.nginx.yml rm --force"
    - "docker-compose -f .cd/docker-compose.nginx.yml up -d --force-recreate"
  environment:
    name: nginx
  artifacts:
    paths:
      - nginx-setting
  only:
    - master
  secret:
    - app.sn-curtain.cert:
        - file: ./nginx-setting/ssl/certificate.crt
    - app.sn-curtain.key:
        - file: ./nginx-setting/ssl/private.key


# Deploy Staging
deploy-staging:
  image: docker:stable
  stage: deploy
  before_script:
    - "apk update"
    - "apk add --no-cache py-pip rsync git openssh"
    - "pip install --no-cache-dir docker-compose"
    - "git submodule update --init --recursive"
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
    - chmod 700 "${HOME}/.ssh/id_rsa"
    - rsync -hrvz --delete --exclude=_ -e "ssh -i ${HOME}/.ssh/id_rsa" entrypoint/ "${LINUX_USERNAME}@${HOST_IP}:/home/$LINUX_USERNAME/entrypoint"

  script:
    - "docker-compose -f .cd/docker-compose.staging.yml pull"
    - "docker-compose -f .cd/docker-compose.staging.yml stop"
    - "docker-compose -f .cd/docker-compose.staging.yml rm --force"
    - "docker-compose -f .cd/docker-compose.staging.yml up -d --force-recreate"
  environment:
    name: staging
    url: "http://dev.sn-curtain.com"
  artifacts:
    paths:
      - entrypoint
  only:
    - master

# Deploy Production
deploy-production:
  stage: deploy
  image: docker:stable
  before_script:
    - "apk update"
    - "apk add --no-cache py-pip rsync git openssh"
    - "pip install --no-cache-dir docker-compose"
    - "git submodule update --init --recursive"
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
    - chmod 700 "${HOME}/.ssh/id_rsa"
    - rsync -hrvz --delete --exclude=_ -e "ssh -i ${HOME}/.ssh/id_rsa" entrypoint/ "${LINUX_USERNAME}@${HOST_IP}:/home/$LINUX_USERNAME/entrypoint"
  script:
    - "docker-compose -f .cd/docker-compose.prod.yml pull"
    - "docker-compose -f .cd/docker-compose.prod.yml stop"
    - "docker-compose -f .cd/docker-compose.prod.yml rm --force"
    - "docker-compose -f .cd/docker-compose.prod.yml up -d --force-recreate"
  environment:
    name: production
    url: "https://sn-curtain.com"
  only:
    - master
  when: manual