# Step
stages:
  - deploy


# When using dind, it's wise to use the overlayfs driver for
# improved performance.few
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: registry.gitlab.com/$CI_PROJECT_PATH

deploy-staging:
  image: docker:stable
  stage: deploy
  before_script:
    - "apk add --no-cache py-pip"
    - "pip install --no-cache-dir docker-compose"
    - "apt-get update"
    - "apt-get --yes --force-yes install git ssh rsync"
    - "git submodule update --init --recursive"

    # - echo "${SSH_PRIVATE_KEY}" > id_rsa
    # - chmod 700 id_rsa
    # - mkdir "${HOME}/.ssh"
    # - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_host"
    # - rsync avh --delete --
  script:
    - mkdir "${HOME}/.ssh"
    - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
    - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
    - echo ${HOME}/.ssh/known_hosts
    - echo ${HOME}/.ssh/id_rsa
    - chmod 700 "${HOME}/.ssh/id_rsa"
    - rsync -hrvz --delete --exclude=_ -e "ssh -i ${HOME}/.ssh/id_rsa" mongo-entrypoint Peaches@sn-curtain.com:/entrypoint
    - "docker-compose -f .cd/docker-compose.staging.yml pull"
    - "docker-compose -f .cd/docker-compose.staging.yml stop"
    - "docker-compose -f .cd/docker-compose.staging.yml rm --force"
    - "docker-compose -f .cd/docker-compose.staging.yml up -d --force-recreate"
  environment:
    name: staging
    url: "http://dev.sn-curtain.com"
  only:
    - master

# Deploy Production
deploy-production:
  stage: deploy
  image: docker:stable
  before_script:
    - "apk add --no-cache py-pip"
    - "pip install docker-compose"
  script:
    - "docker-compose -f .cd/docker-compose.prod.yml pull"
    - "docker-compose -f .cd/docker-compose.prod.yml stop"
    - "docker-compose -f .cd/docker-compose.prod.yml rm --force"
    - "docker-compose -f .cd/docker-compose.prod.yml up -d"
  environment:
    name: production
    url: "https://sn-curtain.com"
  only:
    - master
  when: manual