version: '3'

networks:
  application-tier:

services:
  mongodb-staging:
    image: mongo:3.4-jessie
    container_name: sn-curtain.com-mongodb-staging
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/d
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=$${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=$${MONGO_PASS}
      - MONGO_INITDB_DATABASE=sn-curtain
    volumes:
      - /data/db/dev:/data/db
      - ../script/initdb.js:/docker-entrypoint-initdb.d
    ports:
      - 27018:27017
    command: mongod
  mongodb-express-staging:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$${MONGO_PASS}
