version: '3'

networks:
  application-tier:

services:
  mongodb-staging:
    image: mongo:3.4.2
    container_name: sn-curtain.com-mongodb-staging
    restart: always
    environment:
      # - MONGO_DATA_DIR=/data/d
      # - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1457714577
    volumes:
      - /data/db/dev:/data/db
    ports:
      - 27017:27017
    command: mongod
