version: '3'

networks:
  application-tier:

services:
  mongodb-staging:
    image: mongo:3.4-jessie
    container_name: sn-curtain.com-mongodb-staging
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=sn-${MONGO_DATABASE}
    volumes:
      - /data/db/dev:/data/db
      - ../script/initdb.js:/docker-entrypoint-initdb.d/initdb.js
    ports:
      - 27018:27017
    networks:
      - application-tier
    command: mongod


  # mongodb-express-staging:
  #   image: mongo-express
  #   container_name: sn-curtain.com-mongodb-express-staging
  #   restart: always
  #   links:
  #     - mongodb-staging:mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_PORT=27018
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
  #   networks:
  #     - application-tier