version: '3'

networks:
  application-tier:

services:
  mongodb-prod:
    image: mongo:3.4-jessie
    container_name: sn-curtain.com-mongodb-prod
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/d
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - /data/db/prod:/data/db
    ports:
      - 27019:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
