version: '3'

networks:
  application-tier:

services:
  mongodb-staging:
    image: mongo:3.4-jessie
    container_name: sn-curtain.com-mongodb-staging
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - /data/db/dev:/data/db
      - "/home/${LINUX_USERNAME}/entrypoint:/docker-entrypoint-initdb.d"
    ports:
      - 27018:27017
    networks:
      - application-tier
    command: mongod